os: linux
dist: xenial
language: python
python: '3.7'
compiler: gcc

install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9

- wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.sh -O cmake.sh
- mkdir cmake_alt
- sudo sh cmake.sh --skip-license --prefix=./cmake_alt
- export PATH="$(pwd)/cmake_alt/bin:$PATH"

- sudo apt-get install -qq ninja-build

- pip install conan
- conan user

script:
- mkdir -p build
- cd build
- conan install .. --build=missing
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -G Ninja ..
- cmake --build .
- cmake --install .

- ctest
- cd ../install
- bin/nx_homework_hasher_microservice --version

cache:
    directories:
    - build
    - ~/.conan
