version: 1.0.0.{build}
image: Visual Studio 2019

platform:
- x64

install:
- cmd: choco install ninja
- cmd: set PATH=%PATH%;%PYTHON%/Scripts/
- cmd: pip.exe install conan
- cmd: conan user

build_script:
- cmd: mkdir -p build
- cmd: cd build
- cmd: 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat"'
- cmd: conan install .. --build=missing
- cmd: cmake -G Ninja ..
- cmd: cmake --build .

test_script:
- cmd: cd build
- cmd: ctest

cache:
- build
- '%UserProfile%/.conan'
